export const ANSWERS = [
  "AURAS", "BLAZE", "BLOOM", "BRICK", "BURST", "CANDY", "CHIME", "CLOUD",
  "COMET", "CORAL", "CRANE", "CRISP", "DANCE", "DREAM", "EMBER", "FLARE",
  "FLOAT", "FLORA", "FRAME", "FROST", "GHOST", "GLADE", "GLEAM", "GROVE",
  "HONEY", "HOUSE", "IVORY", "JELLY", "KNACK", "LASER", "LEMON", "LIGHT",
  "LILAC", "LUNAR", "MAGIC", "MANGO", "MAPLE", "MIRTH", "MUSIC", "NERVE",
  "NEXUS", "OASIS", "OCEAN", "OPALS", "ORBIT", "PAINT", "PEARL", "PIXEL",
  "PLUME", "PRISM", "QUART", "QUEST", "QUOTE", "RADAR", "RAVEN", "RHYME", 
  "RIVER", "ROBOT", "ROGUE", "SHINE", "SHOCK", "SKATE", "SOLAR", "SONIC", 
  "SPARK", "SPELL", "SPICE", "SPIRE", "SPORE", "STORM", "SUGAR", "SUNNY", 
  "SWIRL", "TANGO", "THORN", "TIGER", "TRAIL", "ULTRA", "VIBES", "VIVID",
  "WALTZ", "WHIRL", "XENON", "YOUNG", "ZEBRA"
] as const;

export const EXTRA_GUESSES = [
  "ADORE", "ALARM", "ALBUM", "ALIEN", "AMBER", "ANGLE", "APPLE", "ARROW",
  "ATLAS", "AUDIO", "BASIC", "BEACH", "BEGAN", "BERRY", "BLINK", "BOARD",
  "BRAIN", "BRAVE", "BREAD", "BRING", "BRUSH", "CABLE", "CHAIR", "CHARM",
  "CHART", "CHASE", "CHEER", "CHESS", "CHILL", "CHOIR", "CIDER", "CINCH",
  "CIVIC", "CLICK", "CLOCK", "COAST", "COBRA", "COLOR", "COUCH", "COVER",
  "CROWN", "CURVE", "DAISY", "DELTA", "DINGO", "DODGE", "DRAKE", "DRIFT",
  "EAGER", "EARTH", "ELECT", "ELITE", "FAITH", "FANCY", "FIBER", "FIELD",
  "FIEND", "FJORD", "FOCUS", "FORGE", "FRESH", "FRUIT", "GAMER", "GIANT",
  "GLASS", "GLOVE", "GRACE", "GRAPE", "GREEN", "GRIND", "HABIT", "HEART",
  "HINGE", "IDEAL", "IGLOO", "INDEX", "JOKER", "JUMBO", "KARMA", "KAYAK",
  "KOALA", "LAYER", "LEVEL", "LOCAL", "LOTUS", "LUCKY", "METAL", "METER",
  "MIMIC", "MODEL", "MOTOR", "NACHO", "NOBLE", "NOVEL", "OLIVE", "OMEGA",
  "PANEL", "PARTY", "PASTA", "PATCH", "PETAL", "PHASE", "PILOT", "PIVOT",
  "PLANT", "POINT", "POLAR", "POWER", "PULSE", "QUILL", "QUIRK", "RADIO",
  "RAINY", "RATIO", "REACH", "REACT", "RIVER", "SAUCE", "SCENE", "SCOPE",
  "SCORE", "SCOUT", "SERVE", "SHARD", "SHEEN", "SHIFT", "SHOUT", "SIGHT",
  "SKILL", "SLATE", "SLICE", "SMILE", "SMOKE", "SNARE", "SNAKE", "SNOWY",
  "SOLID", "SOUND", "SPACE", "STACK", "STAMP", "STARE", "STEEL", "STILL",
  "STONE", "STYLE", "TABLE", "TASTE", "TEACH", "TEMPO", "THEME", "THRUM",
  "TIDAL", "TIMER", "TOKEN", "TOPAZ", "TORCH", "TOUCH", "TRACE", "TRICK",
  "TROPE", "TULIP", "TWIST", "UNION", "URBAN", "USAGE", "VAPOR", "VENOM",
  "VERSE", "VINYL", "VISTA", "VOICE", "WAGON", "WATER", "WHALE", "WORLD",
  "YEARN", "YIELD", "YODEL", "ZONAL"
];

export const VALID_GUESSES = new Set([...ANSWERS, ...EXTRA_GUESSES]);
